[tox]
envlist = py311
isolated_build = true

[testenv]
deps = -rrequirements-dev.txt
commands =
    ruff check .
    black --check .
    mypy todo_app
    pytest --maxfail=1 --disable-warnings -q --cov=todo_app
